/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: themes\gentaskTheme.ts
 * Command: astryx theme build themes\gentaskTheme.ts --out src\app\styles\gentask.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/**
 * gentask theme — built by `npx astryx theme build`
 * Import the CSS file alongside this module:
 *
 *   import { gentaskTheme } from './gentask';
 *   import './gentask.css';
 */
export const gentaskTheme = {
  name: 'gentask',
  __built: true,
  tokens: {
    "--font-size-4xs": "0.3125rem",
    "--font-size-3xs": "0.4375rem",
    "--font-size-2xs": "0.5rem",
    "--font-size-xs": "0.625rem",
    "--font-size-sm": "0.8125rem",
    "--font-size-base": "1rem",
    "--font-size-lg": "1.25rem",
    "--font-size-xl": "1.5625rem",
    "--font-size-2xl": "1.9375rem",
    "--font-size-3xl": "2.4375rem",
    "--font-size-4xl": "3.0625rem",
    "--font-size-5xl": "3.8125rem",
    "--text-heading-1-size": "var(--font-size-2xl)",
    "--text-heading-1-weight": "var(--font-weight-semibold)",
    "--text-heading-1-leading": "1.4194",
    "--text-heading-2-size": "var(--font-size-xl)",
    "--text-heading-2-weight": "var(--font-weight-semibold)",
    "--text-heading-2-leading": "1.44",
    "--text-heading-3-size": "var(--font-size-lg)",
    "--text-heading-3-weight": "var(--font-weight-semibold)",
    "--text-heading-3-leading": "1.4",
    "--text-heading-4-size": "var(--font-size-base)",
    "--text-heading-4-weight": "var(--font-weight-semibold)",
    "--text-heading-4-leading": "1.5",
    "--text-heading-5-size": "var(--font-size-sm)",
    "--text-heading-5-weight": "var(--font-weight-semibold)",
    "--text-heading-5-leading": "1.5385",
    "--text-heading-6-size": "var(--font-size-xs)",
    "--text-heading-6-weight": "var(--font-weight-semibold)",
    "--text-heading-6-leading": "1.6",
    "--text-body-size": "var(--font-size-base)",
    "--text-body-weight": "var(--font-weight-normal)",
    "--text-body-leading": "1.5",
    "--text-large-size": "var(--font-size-lg)",
    "--text-large-weight": "var(--font-weight-semibold)",
    "--text-large-leading": "1.4",
    "--text-label-size": "var(--font-size-base)",
    "--text-label-weight": "var(--font-weight-medium)",
    "--text-label-leading": "1.5",
    "--text-code-size": "var(--font-size-base)",
    "--text-code-weight": "var(--font-weight-normal)",
    "--text-code-leading": "1.5",
    "--text-supporting-size": "var(--font-size-sm)",
    "--text-supporting-weight": "var(--font-weight-normal)",
    "--text-supporting-leading": "1.5385",
    "--text-display-1-size": "var(--font-size-5xl)",
    "--text-display-1-weight": "var(--font-weight-normal)",
    "--text-display-1-leading": "1.2459",
    "--text-display-2-size": "var(--font-size-4xl)",
    "--text-display-2-weight": "var(--font-weight-normal)",
    "--text-display-2-leading": "1.2245",
    "--text-display-3-size": "var(--font-size-3xl)",
    "--text-display-3-weight": "var(--font-weight-normal)",
    "--text-display-3-leading": "1.2308",
    "--duration-fast-min": "95ms",
    "--duration-fast": "125ms",
    "--duration-fast-max": "165ms",
    "--duration-medium-min": "225ms",
    "--duration-medium": "300ms",
    "--duration-medium-max": "400ms",
    "--duration-slow-min": "525ms",
    "--duration-slow": "700ms",
    "--duration-slow-max": "935ms",
    "--font-family-body": "\"DM Sans\", -apple-system, BlinkMacSystemFont, \"Segoe UI\", Roboto, Helvetica, Arial, sans-serif",
    "--font-family-heading": "\"Playwrite US Trad\", Georgia, \"Times New Roman\", Times, serif",
    "--font-family-code": "\"JetBrains Mono\", \"SF Mono\", Monaco, Consolas, monospace",
    "--color-syntax-keyword": "light-dark(#5a6b2a, #a8bf6a)",
    "--color-syntax-string": "light-dark(#2e6b4a, #7bc49e)",
    "--color-syntax-comment": "light-dark(#707E46, #707E46)",
    "--color-syntax-number": "light-dark(#8c6b30, #d4b870)",
    "--color-syntax-function": "light-dark(#3a5e8c, #7ba8d4)",
    "--color-syntax-type": "light-dark(#6b4a8c, #b08ed4)",
    "--color-syntax-variable": "light-dark(#3E481D, #C0CBA9)",
    "--color-syntax-operator": "light-dark(#707E46, #94a468)",
    "--color-syntax-constant": "light-dark(#8c6b30, #d4b870)",
    "--color-syntax-tag": "light-dark(#8c3a3a, #d47a7a)",
    "--color-syntax-attribute": "light-dark(#7c5e3a, #c4a882)",
    "--color-syntax-property": "light-dark(#3a7c6b, #70c4b0)",
    "--color-syntax-punctuation": "light-dark(#566a39, #92af6a)",
    "--color-syntax-background": "light-dark(#F0F0E0, #1a1c14)",
    "--color-accent": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
    "--color-accent-muted": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-neutral": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-background-surface": "light-dark(oklch(0.995 0.002 110), oklch(0.215 0.01 118))",
    "--color-background-body": "light-dark(oklch(0.97 0.006 110), oklch(0.175 0.008 118))",
    "--color-overlay": "light-dark(oklch(0.18 0.01 110 / 0.45), oklch(0 0 0 / 0.6))",
    "--color-overlay-hover": "light-dark(oklch(0.23 0.015 110 / 0.04), oklch(0.96 0.005 110 / 0.06))",
    "--color-overlay-pressed": "light-dark(oklch(0.23 0.015 110 / 0.08), oklch(0.96 0.005 110 / 0.1))",
    "--color-background-muted": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
    "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
    "--color-text-disabled": "light-dark(oklch(0.63 0.02 110), oklch(0.58 0.02 110))",
    "--color-text-accent": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
    "--color-on-dark": "#f2f2ee",
    "--color-on-light": "#1d1e16",
    "--color-on-accent": "light-dark(oklch(0.99 0.02 118), oklch(0.18 0.03 118))",
    "--color-on-success": "light-dark(oklch(0.99 0.003 110), oklch(0.18 0.008 118))",
    "--color-on-error": "light-dark(oklch(0.99 0.003 110), oklch(0.18 0.008 118))",
    "--color-on-warning": "light-dark(#1d1e16, oklch(0.18 0.008 118))",
    "--color-icon-accent": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
    "--color-icon-primary": "light-dark(#1d1e16, #f2f2ee)",
    "--color-icon-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
    "--color-icon-disabled": "light-dark(oklch(0.63 0.02 110), oklch(0.58 0.02 110))",
    "--color-background-card": "light-dark(oklch(0.995 0.002 110), oklch(0.215 0.01 118))",
    "--color-background-popover": "light-dark(#ffffff, #22241d)",
    "--color-background-inverted": "light-dark(#1d1e16, #f2f2ee)",
    "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))",
    "--color-success-muted": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
    "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))",
    "--color-error-muted": "light-dark(#ffe5e1, #4d2623)",
    "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))",
    "--color-warning-muted": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
    "--color-border": "light-dark(oklch(0.915 0.008 110), oklch(1 0 0 / 0.1))",
    "--color-border-emphasized": "light-dark(oklch(0.85 0.012 110), oklch(1 0 0 / 0.2))",
    "--color-skeleton": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-shadow": "light-dark(oklch(0.18 0.01 110 / 0.1), oklch(0 0 0 / 0.4))",
    "--color-tint-hover": "light-dark(black, white)",
    "--color-background-blue": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-border-blue": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-icon-blue": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-text-blue": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-background-cyan": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-border-cyan": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-icon-cyan": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-text-cyan": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-background-gray": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-border-gray": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))",
    "--color-icon-gray": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
    "--color-text-gray": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
    "--color-background-green": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
    "--color-border-green": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
    "--color-icon-green": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))",
    "--color-text-green": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))",
    "--color-background-orange": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
    "--color-border-orange": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
    "--color-icon-orange": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))",
    "--color-text-orange": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))",
    "--color-background-pink": "light-dark(#ffe5e1, #4d2623)",
    "--color-border-pink": "light-dark(#ffe5e1, #4d2623)",
    "--color-icon-pink": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))",
    "--color-text-pink": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))",
    "--color-background-purple": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-border-purple": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
    "--color-icon-purple": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-text-purple": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))",
    "--color-background-red": "light-dark(#ffe5e1, #4d2623)",
    "--color-border-red": "light-dark(#ffe5e1, #4d2623)",
    "--color-icon-red": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))",
    "--color-text-red": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))",
    "--color-background-teal": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
    "--color-border-teal": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
    "--color-icon-teal": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))",
    "--color-text-teal": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))",
    "--color-background-yellow": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
    "--color-border-yellow": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
    "--color-icon-yellow": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))",
    "--color-text-yellow": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))",
    "--spacing-0-5": "3px",
    "--spacing-1": "6px",
    "--spacing-1-5": "9px",
    "--spacing-2": "12px",
    "--spacing-3": "18px",
    "--spacing-4": "24px",
    "--spacing-5": "30px",
    "--spacing-6": "36px",
    "--spacing-7": "42px",
    "--spacing-8": "48px",
    "--spacing-9": "54px",
    "--spacing-10": "60px",
    "--spacing-11": "66px",
    "--spacing-12": "72px",
    "--radius-inner": "6px",
    "--radius-element": "12px",
    "--radius-container": "18px",
    "--radius-page": "42px",
    "--size-element-sm": "36px",
    "--size-element-md": "40px",
    "--size-element-lg": "44px",
    "--shadow-low": "0 2px 4px #3E481D0D, 0 4px 8px #3E481D1A",
    "--shadow-med": "0 2px 4px #3E481D0D, 0 4px 12px #3E481D1A",
    "--shadow-high": "0 4px 6px #3E481D1A, 0 12px 24px #3E481D26",
    "--shadow-inset-hover": "inset 0px 0px 0px 2px #3E481D30",
    "--shadow-inset-selected": "inset 0px 0px 0px 2px #3E481D50",
    "--shadow-inset-success": "light-dark(inset 0 0 0 2px oklch(0.95 0.04 150), inset 0 0 0 2px oklch(0.3 0.05 150))",
    "--shadow-inset-warning": "light-dark(inset 0 0 0 2px oklch(0.95 0.05 80), inset 0 0 0 2px oklch(0.32 0.05 80))",
    "--shadow-inset-error": "light-dark(inset 0 0 0 2px #ffe5e1, inset 0 0 0 2px #4d2623)"
  },
  components: {
    "heading": {
      "level:1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-1-size)",
        "fontWeight": "var(--text-heading-1-weight)",
        "lineHeight": "var(--text-heading-1-leading)"
      },
      "level:2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-2-size)",
        "fontWeight": "var(--text-heading-2-weight)",
        "lineHeight": "var(--text-heading-2-leading)"
      },
      "level:3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-3-size)",
        "fontWeight": "var(--text-heading-3-weight)",
        "lineHeight": "var(--text-heading-3-leading)"
      },
      "level:4": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-4-size)",
        "fontWeight": "var(--text-heading-4-weight)",
        "lineHeight": "var(--text-heading-4-leading)"
      },
      "level:5": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-5-size)",
        "fontWeight": "var(--text-heading-5-weight)",
        "lineHeight": "var(--text-heading-5-leading)"
      },
      "level:6": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-heading-6-size)",
        "fontWeight": "var(--text-heading-6-weight)",
        "lineHeight": "var(--text-heading-6-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "text": {
      "type:body": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-body-size)",
        "lineHeight": "var(--text-body-leading)"
      },
      "type:large": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-large-size)",
        "lineHeight": "var(--text-large-leading)"
      },
      "type:label": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-label-size)",
        "lineHeight": "var(--text-label-leading)"
      },
      "type:code": {
        "fontFamily": "var(--font-family-code)",
        "fontSize": "var(--text-code-size)",
        "lineHeight": "var(--text-code-leading)"
      },
      "type:supporting": {
        "fontFamily": "var(--font-family-body)",
        "fontSize": "var(--text-supporting-size)",
        "lineHeight": "var(--text-supporting-leading)"
      },
      "type:display-1": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-1-size)",
        "lineHeight": "var(--text-display-1-leading)"
      },
      "type:display-2": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-2-size)",
        "lineHeight": "var(--text-display-2-leading)"
      },
      "type:display-3": {
        "fontFamily": "var(--font-family-heading)",
        "fontSize": "var(--text-display-3-size)",
        "lineHeight": "var(--text-display-3-leading)"
      }
    },
    "button": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "variant:secondary": {
        "borderColor": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
        "color": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
        ":hover": {
          "backgroundColor": "light-dark(oklch(0.95 0.04 118), oklch(0.3 0.05 118))"
        }
      },
      "variant:ghost": {
        "color": "var(--color-text-secondary)",
        ":hover": {
          "color": "var(--color-text-primary)"
        },
        ":focus-visible": {
          "color": "var(--color-text-primary)"
        }
      },
      "variant:destructive": {
        "backgroundColor": "light-dark(#ffe5e1, #4d2623)",
        "color": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "card": {
      "base": {
        "borderRadius": "var(--radius-page)",
        "padding": "var(--spacing-3)"
      },
      "variant:info": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:success": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:warning": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:error": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:blue": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:cyan": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:gray": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:green": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:orange": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:pink": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:purple": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:red": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:teal": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:yellow": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "variant:muted": {
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      }
    },
    "section": {
      "base": {
        "padding": "var(--spacing-3)"
      }
    },
    "popover-surface": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      }
    },
    "dialog": {
      "variant:standard": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      }
    },
    "bottom-sheet": {
      "base": {
        "borderStartStartRadius": "1.5rem",
        "borderStartEndRadius": "1.5rem",
        "cornerStartStartShape": "superellipse(1.6)",
        "cornerStartEndShape": "superellipse(1.6)"
      }
    },
    "toast": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)",
        "backgroundColor": "var(--color-background-popover)",
        "color": "var(--color-text-primary)",
        "borderWidth": "var(--border-width)",
        "borderStyle": "solid",
        "borderColor": "var(--color-border-emphasized)"
      },
      "type:error": {
        "backgroundColor": "var(--color-error-muted)",
        "borderColor": "var(--color-error)"
      }
    },
    "side-nav-item": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      }
    },
    "app-shell-sidenav": {
      "base": {
        "backgroundColor": "var(--color-background-body)"
      }
    },
    "top-nav-heading": {
      "base": {
        "color": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))",
        "--color-text-primary": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))"
      }
    },
    "top-nav-item": {
      "base": {
        "color": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))"
      },
      "selected": {
        "color": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))"
      }
    },
    "badge": {
      "variant:info": {
        "backgroundColor": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
        "color": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))"
      },
      "variant:neutral": {
        "backgroundColor": "light-dark(oklch(0.95 0.04 118), oklch(0.3 0.05 118))",
        "color": "light-dark(oklch(0.5 0.105 118), oklch(0.68 0.12 118))"
      },
      "variant:success": {
        "backgroundColor": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
        "color": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "variant:warning": {
        "backgroundColor": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
        "color": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "variant:error": {
        "backgroundColor": "light-dark(#ffe5e1, #4d2623)",
        "color": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "banner": {
      "status:info": {
        "--color-accent-muted": "light-dark(oklch(0.95 0.04 235), oklch(0.3 0.05 235))",
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
        "--color-accent": "light-dark(oklch(0.58 0.1 235), oklch(0.72 0.11 235))"
      },
      "status:success": {
        "--color-success-muted": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning-muted": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error-muted": "light-dark(#ffe5e1, #4d2623)",
        "--color-text-primary": "light-dark(#1d1e16, #f2f2ee)",
        "--color-text-secondary": "light-dark(oklch(0.47 0.02 110), oklch(0.74 0.02 110))",
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "progressbar-track": {
      "base": {
        "backgroundColor": "light-dark(oklch(0.945 0.008 110), oklch(0.285 0.014 118))"
      }
    },
    "progressbar-fill": {
      "variant:success": {
        "backgroundColor": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "variant:warning": {
        "backgroundColor": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "variant:error": {
        "backgroundColor": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "field-status": {
      "type:success": {
        "backgroundColor": "light-dark(oklch(0.95 0.04 150), oklch(0.3 0.05 150))",
        "color": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "type:warning": {
        "backgroundColor": "light-dark(oklch(0.95 0.05 80), oklch(0.32 0.05 80))",
        "color": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "type:error": {
        "backgroundColor": "light-dark(#ffe5e1, #4d2623)",
        "color": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "text-input": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "textarea": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "number-input": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "date-input": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "time-input": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "selector": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "multi-selector": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "typeahead": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    },
    "tokenizer": {
      "base": {
        "borderRadius": "1.5rem",
        "cornerShape": "superellipse(1.6)"
      },
      "status:success": {
        "--color-success": "light-dark(oklch(0.55 0.13 150), oklch(0.72 0.14 150))"
      },
      "status:warning": {
        "--color-warning": "light-dark(oklch(0.64 0.13 75), oklch(0.78 0.13 80))"
      },
      "status:error": {
        "--color-error": "light-dark(oklch(0.56 0.2 25), oklch(0.7 0.17 25))"
      }
    }
  },
  __onDark: {
    "tokens": {
      "color-scheme": "dark",
      "--color-text-primary": "#f2f2ee",
      "--color-icon-primary": "#f2f2ee",
      "--color-accent": "oklch(0.68 0.12 118)"
    }
  },
  __onLight: {
    "tokens": {
      "color-scheme": "light",
      "--color-text-primary": "#1d1e16",
      "--color-icon-primary": "#1d1e16",
      "--color-accent": "oklch(0.5 0.105 118)"
    }
  },

};
