/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: themes/gentaskTheme.ts
 * Command: astryx theme build themes/gentaskTheme.ts --out src/app/styles/gentask.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}

declare module '@astryxdesign/core/Card' {
  interface CardVariantMap {
    'info': true;
    'success': true;
    'warning': true;
    'error': true;
  }
}

declare module '@astryxdesign/core/ProgressBar' {
  interface ProgressBarVariantMap {
    'success': true;
    'warning': true;
    'error': true;
  }
}
