/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: themes/gentaskTheme.ts
 * Command: astryx theme build themes/gentaskTheme.ts --out src/app/styles/gentask.css
 * CLI: @astryxdesign/cli@0.5.2
 * Core: @astryxdesign/core@0.5.2
 */

/// <reference path="./gentask.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const gentaskTheme: DefinedTheme;
